### ISSUE TITLE
Boot script timeout of 1 second - fconfig-linux.bin

### ISSUE THREAD

**Issue by rossjparker** [vtss/flash_builder#1]
I'd like to change the boot script timeout for my build to 1 second (down from the default 3 seconds) - so I need to change fconfig-linux.bin. This is a binary file and there are no instructions or make methods to generate this file. How can I change it?

**Comment by lpovlsen** [comment]
Hi Ross!

The RedBoot config section is best created by RedBoot itself (with `fconfig`). Once you boot your system, you can use a shell and dd out the data and scp it to your flashbuilder host. 

    # debug sys sh
    / # cat /proc/mtd
    dev:    size   erasesize  name
    mtd0: 00040000 00010000 "RedBoot"
    mtd1: 00010000 00010000 "conf"
    mtd2: 00fc0000 00010000 "linux.bk"
    mtd3: 00fc0000 00010000 "linux"
    mtd4: 00010000 00010000 "FIS_directory"
    mtd5: 00010000 00010000 "RedBoot_config"
    mtd6: 00010000 00010000 "Redundant_FIS"
    mtd7: 10000000 00020000 "rootfs_data"
    / # dd if=/dev/mtd5 of=/tmp/fconfig.bin bs=64k
    1+0 records in
    1+0 records out

**Comment by rossjparker** [comment]
Thanks Lars!
Can I suggest adding a README file in the `files` directory with this information for future reference?
Regards,
Ross.
